### PR TITLE
promisify functions

### PR DESCRIPTION
**Pull request by vernak2539**

### CODE REVIEW

**Comment by vernak2539** [comment]
Just need to test the coverage. Cannot test on a windows machine b/c istanbul won't work

**Comment by vernak2539** [comment]
```
=============================== Coverage summary ===============================
Statements   : 92.21% ( 71/77 )
Branches     : 85.94% ( 55/64 )
Functions    : 100% ( 10/10 )
Lines        : 92.21% ( 71/77 )
================================================================================
````

**Comment by vernak2539** [comment]
@dougwilson could you take a look at these changes when you have a chance? Need to know if I missed something

**Comment by dougwilson** [comment]
@vernak2539 I went ahead and skimmed over this an generally LGTM. The pattern where you accept a callback _or_ return a promise I've seen before I don't really have any reason to dislike :)

**Comment by vernak2539** [comment]
Great, thanks for taking a look. Have you seen a better/different pattern before? Would you happen to have an example?

**Comment by dougwilson** [comment]
I've only seen these patterns:

1. Only return promises; do not provide a callback interface (the worst).
2. Only provide a callback; do not provide a promise interface (best compatibility, because any promise library can turn Node.js-style callback functions into promises).
3. Hybrid (what is being done here).

**Pull request merged**
